# Generated by Django 5.0.6 on 2024-06-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cadastral_number', models.CharField(max_length=50, verbose_name='кадастровый_номер')),
                ('latitude', models.CharField(max_length=20, verbose_name='широта')),
                ('longitute', models.CharField(max_length=20, verbose_name='долгота')),
                ('response', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
