# Generated by Django 5.0.6 on 2024-06-08 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo_service', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='querylog',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
